AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-app-stepfunctions

  Sample SAM Template for sample-app-stepfunctions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Parameters:
  StockCheckerFunctionReservedConcurrency:
    Type: String
    Default: 10

  StockSellerFunctionReservedConcurrency:
    Type: String
    Default: 10

  StockBuyerFunctionReservedConcurrency:
    Type: String
    Default: 10

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/stockTrader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !Ref StockCheckerFunction.Alias
        StockSellerFunctionArn: !Ref StockSellerFunction.Alias
        StockBuyerFunctionArn: !Ref StockBuyerFunction.Alias
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction.Alias
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction.Alias
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction.Alias
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/StockChecker
      Handler: StockChecker.src.main.java.stockChecker.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 100
      Description: Sample SAM lambda function
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: !Sub ${StockCheckerFunctionReservedConcurrency}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

  StockCheckerFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "", [ "/aws/lambda/", !Ref StockCheckerFunction ] ]
      RetentionInDays: 365

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/StockSeller
      Handler: StockSeller.src.main.java.stockSeller.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 100
      Description: Sample SAM lambda function
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: !Sub ${StockSellerFunctionReservedConcurrency}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

  StockSellerFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "", [ "/aws/lambda/", !Ref StockSellerFunction ] ]
      RetentionInDays: 365

  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/StockBuyer
      Handler: StockBuyer.src.main.java.stockBuyer.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 100
      Description: Sample SAM lambda function
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: !Sub ${StockBuyerFunctionReservedConcurrency}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

  StockBuyerFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "", [ "/aws/lambda/", !Ref StockBuyerFunction ] ]
      RetentionInDays: 365

  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StockTradingStateMachineArn:
    Description: "Stock Trading State machine ARN"
    Value: !Ref StockTradingStateMachine
    Export:
      Name: !Sub '${AWS::StackName}:StockTradingStateMachineArn'

  StockTradingStateMachineRoleArn:
    Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
    Value: !GetAtt StockTradingStateMachineRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}:StockTradingStateMachineRoleArn'

  StockCheckerFunctionName:
    Description: lambda name
    Value: !Ref StockCheckerFunction
    Export:
      Name: !Sub '${AWS::StackName}:StockCheckerFunctionName'

  StockSellerFunctionName:
    Description: lambda name
    Value: !Ref StockSellerFunction
    Export:
      Name: !Sub '${AWS::StackName}:StockSellerFunctionName'

  StockBuyerFunctionName:
    Description: lambda name
    Value: !Ref StockBuyerFunction
    Export:
      Name: !Sub '${AWS::StackName}:StockBuyerFunctionName'