name: ci-checks

on: push

jobs:

  cfnlint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cfnlint
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./template.yaml

  cfnnag:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cfnnag
        uses: stelligent/cfn_nag@master
        with:
          input_path: template.yaml
          extra_args: ''

  cfnguard:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - run: |
          echo "${{env.GITHUB_WORKSPACE}}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfnguard-reliability
        uses: grolston/guard-action@main
        with:
          data_directory: './cloudformation/'
          rule_set: wa-Reliability-Pillar

      - name: cfnguard-security
        uses: grolston/guard-action@main
        with:
          data_directory: './cloudformation/'
          rule_set: wa-Security-Pillar
