name: ci-actions-volatile

on:
  push:
    branches:
      - 'main'
#  workflow_run: # initiate after checks are completed
#    workflows: ["ci-checks"]
#    branches:
#      - 'main'
#    types: [completed]

jobs:

  #  if_checks_failed:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #    steps:
  #      - name: Checks failed.
  #        shell: bash
  #        run: |
  #          echo "Checks failed." # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
  #          exit 1
  #
  #  if_checks_succeeded:
  #    runs-on: ubuntu-latest
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #    steps:
  #      - name: Checks passed.
  #        shell: bash
  #        run: |
  #          echo "Checks succeeded." # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
  #          exit 0

  sam_deploy:
    # needs: if_checks_succeeded
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      awsaccount_tools: '905618979966'
      awsaccount_target: '887977420079'
      environment: sand
      app_name: sample-app-stepfunctions
      stack_name: sample-app-stepfunctions-sand
      system: sample
    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::887977420079:role/tbs-ci
      # Build inside Docker containers
      - run: sam build --use-container
      - run: |
          echo Running against environment: $environment, account: $awsaccount_target
          echo using deploy bucket: devops-ap-southeast-2-905618979966-deploy
          sam deploy --template-file ./.aws-sam/build/template.yaml --stack-name sample-app-stepfunctions-sand \
            --role-arn "arn:aws:iam::887977420079:role/tbs-cfnexec-ci" \
            --s3-bucket devops-ap-southeast-2-905618979966-deploy --s3-prefix volatile/sam/$stack_name \
            --capabilities CAPABILITY_IAM --region ap-southeast-2 --no-fail-on-empty-changeset \
            --tags stackname=sample-app-stepfunctions-sand environment=sand system=sample