name: ci-actions-volatile

on:
  workflow_run: # initiate after checks are completed
    workflows: ["ci-checks"]
    branches:
      - 'feature/**'
      - 'main'
    types: [completed]

env:
  awsaccount_tools: '905618979966'
  awsaccount_target: '887977420079'
  environment: sand
  app_name: sample-app-stepfunctions
  stack_name: sample-app-stepfunctions-sand
  system: sample
jobs:

  if_checks_failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checks failed.
        shell: bash
        run: |
          echo "Checks failed." # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
          exit 1

  if_checks_succeeded:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checks passed.
        shell: bash
        run: |
          echo "Checks succeeded." # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
          exit 0

  sam_deploy:
    needs: if_checks_succeeded
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: EnvVars
        run: |
          echo "Deploying to target environment: ${{env.environment}}, account ${{env.awsaccount_target}}"
      - name: Checkout.
        uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-duration-seconds: 1200
          role-to-assume: arn:aws:iam::${{env.awsaccount_target}}:role/tbs-ci
      # Build inside Docker containers
      - run: sam build -t ./cloudformation/template.yaml --use-container
      - run: |
          echo Running against environment: ${{env.environment}}, account: ${{env.awsaccount_target}}
          sam deploy --template-file ./.aws-sam/build/template.yaml --stack-name ${{env.stack_name}} \
            --role-arn "arn:aws:iam::${{env.awsaccount_target}}:role/tbs-cfnexec-ci" \
            --s3-bucket devops-ap-southeast-2-905618979966-deploy --s3-prefix volatile/sam/${{env.stack_name}} \
            --capabilities CAPABILITY_IAM --region ap-southeast-2 --no-fail-on-empty-changeset \
            --tags stackname=${{env.stack_name}} environment=${{env.environment}} system=${{env.system}}